/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    events: Event;
    musicians: Musician;
    'recurring-series': RecurringSery;
    'menu-categories': MenuCategory;
    'menu-items': MenuItem;
    rooms: Room;
    'team-members': TeamMember;
    testimonials: Testimonial;
    'artist-applications': ArtistApplication;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    musicians: MusiciansSelect<false> | MusiciansSelect<true>;
    'recurring-series': RecurringSeriesSelect<false> | RecurringSeriesSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'artist-applications': ArtistApplicationsSelect<false> | ArtistApplicationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'pl') | ('en' | 'pl')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'opening-hours': OpeningHour;
    legal: Legal;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'opening-hours': OpeningHoursSelect<false> | OpeningHoursSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
  };
  locale: 'en' | 'pl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  layout?:
    | (
        | PageHeroBlock
        | {
            heading?: string | null;
            subtext?: string | null;
            /**
             * Używane jako plakat filmu (przed załadowaniem) i fallback dla osób z ograniczoną animacją. Bez filmu — pełne tło.
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Film w tle hero — leci automatycznie, w pętli, wyciszony, lekko przyciemniony. Np. /videos/hero-banner.mp4. Zostaw puste, aby użyć tylko zdjęcia.
             */
            backgroundVideoUrl?: string | null;
            secondaryLinks?:
              | {
                  link?: {
                    type?: ('reference' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'posts';
                          value: number | Post;
                        } | null);
                    url?: string | null;
                    label?: string | null;
                  };
                  icon?: ('none' | 'fork' | 'music' | 'ticket' | 'calendar') | null;
                  id?: string | null;
                }[]
              | null;
            ctaLink?: {
              type?: ('reference' | 'custom') | null;
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
              label?: string | null;
            };
            ctaIcon?: ('none' | 'fork' | 'music' | 'ticket' | 'calendar') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | AboutIntroBlock
        | BentoSectionBlock
        | MenuSectionBlock
        | SetMenuBlock
        | PromoBandBlock
        | EventsTeaserBlock
        | SpecialEventsBlock
        | EventsCalendarBlock
        | MusiciansGridBlock
        | RecurringSeriesTeaserBlock
        | NewsCarouselBlock
        | RoomSelectorBlock
        | OfferCardsBlock
        | SalesContactBlock
        | EveningPhasesBlock
        | ContactInfoBlock
        | MapEmbedBlock
        | ArtistCtaBlock
        | Notice21PlusBlock
        | NewsletterCtaBlock
        | ArtistFormBlock
        | TestimonialsBlock
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            title: string;
            embedUrl: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'liveStream';
          }
        | {
            columns?:
              | {
                  size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  enableLink?: boolean | null;
                  link?: {
                    type?: ('reference' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'posts';
                          value: number | Post;
                        } | null);
                    url?: string | null;
                    label?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            richText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            links?:
              | {
                  link?: {
                    type?: ('reference' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'posts';
                          value: number | Post;
                        } | null);
                    url?: string | null;
                    label?: string | null;
                    /**
                     * Choose how the link should be rendered.
                     */
                    appearance?: ('default' | 'outline') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            media: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            introContent?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            populateBy?: ('collection' | 'selection') | null;
            relationTo?: ('posts' | 'pages') | null;
            categories?: (number | Category)[] | null;
            limit?: number | null;
            selectedDocs?:
              | (
                  | {
                      relationTo: 'pages';
                      value: number | Page;
                    }
                  | {
                      relationTo: 'posts';
                      value: number | Post;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'archive';
          }
        | {
            style: 'info' | 'warning' | 'error' | 'success';
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock".
 */
export interface PageHeroBlock {
  eyebrow?: string | null;
  title: string;
  titleStyle?: ('serif' | 'uppercase') | null;
  backgroundImage?: (number | null) | Media;
  inlineLinkLabel?: string | null;
  inlineLinkUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Short summary shown on news cards
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  categories?: (number | Category)[] | null;
  relatedPosts?: (number | Post)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutIntroBlock".
 */
export interface AboutIntroBlock {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  body?: string | null;
  /**
   * Italic quote
   */
  pullQuote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoSectionBlock".
 */
export interface BentoSectionBlock {
  subheading?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Each item is a bento card. Set colSpan to control layout.
   */
  items?:
    | {
        image?: (number | null) | Media;
        /**
         * Controls how wide this card is in the grid
         */
        colSpan: 'half' | 'full';
        /**
         * Small description text above title
         */
        label?: string | null;
        title: string;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bentoSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenuSectionBlock".
 */
export interface MenuSectionBlock {
  sectionTag?: string | null;
  heading?: string | null;
  /**
   * Which menu-items to show
   */
  menuType: 'cigars' | 'cocktails' | 'wine' | 'food';
  layout: 'pricedList' | 'cardGrid';
  groupByCategory?: boolean | null;
  /**
   * ZOBACZ CAŁE MENU (PDF)
   */
  pdfDownload?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'menuSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SetMenuBlock".
 */
export interface SetMenuBlock {
  heading?: string | null;
  dateLabel?: string | null;
  menus?:
    | {
        name?: string | null;
        price?: number | null;
        courses?:
          | {
              courseLabel?: string | null;
              dish?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'setMenu';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBandBlock".
 */
export interface PromoBandBlock {
  heading?: string | null;
  body?: string | null;
  image?: (number | null) | Media;
  items?:
    | {
        label?: string | null;
        sub?: string | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  relatedEvent?: (number | null) | Event;
  style?: ('gold' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'promoBand';
}
/**
 * Every event is a single, individually-created entry with one concrete date & time. Only one event is allowed per calendar day (Europe/Warsaw), and events cannot be scheduled on Mondays (the club is closed). To set up a similar event (e.g. another night in a series), open an existing one and use the “Duplicate” action, then change the date and details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title?: string | null;
  /**
   * Controls badge/styling on the program + detail pages
   */
  eventType?: ('standard' | 'special') | null;
  /**
   * Eyebrow above the title (e.g. "Muzyka na żywo", "Recital")
   */
  leadTitle?: string | null;
  /**
   * Short description shown on event cards and the calendar popover
   */
  description?: string | null;
  /**
   * Photo shown as card background
   */
  image?: (number | null) | Media;
  /**
   * Poster artwork (used in the special-events carousel)
   */
  posterImage?: (number | null) | Media;
  /**
   * Start date and time of the event (Europe/Warsaw). Only one event per day is allowed, and Mondays are not allowed (the club is closed on Mondays).
   */
  date?: string | null;
  /**
   * End time in HH:MM format
   */
  endTime?: string | null;
  /**
   * Ticket price in PLN (leave empty if free)
   */
  price?: number | null;
  /**
   * Make this event available for manual teaser selection
   */
  featured?: boolean | null;
  /**
   * Which room/strefa
   */
  room?: (number | null) | Room;
  /**
   * Themed series this event belongs to (e.g. Jazzowe Wtorki). The series page lists every event linked here.
   */
  recurringSeries?: (number | null) | RecurringSery;
  /**
   * Genre/category chips (JAZZ, SWING, MUZYKA KLASYCZNA…)
   */
  genres?: (number | Category)[] | null;
  performers?:
    | {
        musician?: (number | null) | Musician;
        instrument?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Heading above the long description on the event detail page
   */
  descriptionHeading?: string | null;
  /**
   * Full description shown on the event detail page
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * External URL to buy tickets
   */
  ticketUrl?: string | null;
  /**
   * Overrides the global reservation link
   */
  reservationUrl?: string | null;
  /**
   * Show social share buttons on the event detail page
   */
  shareEnabled?: boolean | null;
  /**
   * Heading above the performers grid
   */
  performersHeading?: string | null;
  /**
   * Label above the share buttons (visibility is controlled by “Show social share buttons”)
   */
  shareLabel?: string | null;
  /**
   * Show the "Nadchodzące wydarzenia" strip at the bottom
   */
  showUpcoming?: boolean | null;
  upcomingHeading?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bookable rooms and spaces (e.g. VIP ROOM).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Maximum number of guests ("do N osób")
   */
  capacity?: number | null;
  description?: string | null;
  equipment?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls display order (lower numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recurring event series with their own branding and gallery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-series".
 */
export interface RecurringSery {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Series logo/wordmark
   */
  wordmarkImage?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  themeColor?: ('amber' | 'blackwhite' | 'sepia' | 'purple') | null;
  eyebrow?: string | null;
  description?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Heading for the upcoming-events band (events derive from the Events collection)
   */
  upcomingHeading?: string | null;
  /**
   * How many upcoming events to list
   */
  upcomingCount?: number | null;
  seeProgrammeLabel?: string | null;
  /**
   * Show the "other recurring series" section
   */
  showOtherSeries?: boolean | null;
  otherSeriesHeading?: string | null;
  /**
   * Show the "news" (Aktualności) section
   */
  showNews?: boolean | null;
  newsHeading?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Musicians and performers. Each has their own artist page (click a tile) with an editable bio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "musicians".
 */
export interface Musician {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  instrument?: string | null;
  /**
   * Optional role/eyebrow on the artist page (e.g. „Wokalistka”, „Lider zespołu”)
   */
  role?: string | null;
  /**
   * Tile photo (also used as the artist page header if no header image is set)
   */
  photo?: (number | null) | Media;
  /**
   * Optional large header image for the artist page (falls back to the tile photo)
   */
  heroImage?: (number | null) | Media;
  /**
   * Short bio (lead paragraph on the artist page)
   */
  bio?: string | null;
  /**
   * Full biography / content shown on the artist’s page
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Controls display order (lower numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsTeaserBlock".
 */
export interface EventsTeaserBlock {
  eyebrow?: string | null;
  heading?: string | null;
  viewAllLabel?: string | null;
  viewAllUrl?: string | null;
  limit?: number | null;
  onlyFeatured?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventsTeaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecialEventsBlock".
 */
export interface SpecialEventsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'specialEvents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsCalendarBlock".
 */
export interface EventsCalendarBlock {
  /**
   * Choose how the calendar is displayed
   */
  variant?: ('teaser' | 'full') | null;
  /**
   * Background style for the teaser carousel
   */
  colorScheme?: ('gold' | 'white') | null;
  heading?: string | null;
  /**
   * CTA button label
   */
  ctaLabel?: string | null;
  /**
   * CTA button URL
   */
  ctaUrl?: string | null;
  /**
   * How to populate the teaser carousel
   */
  eventsSource?: ('auto' | 'manual') | null;
  /**
   * How many upcoming events to show
   */
  autoCount?: number | null;
  /**
   * Select specific events to show in the teaser (only events marked as Featured appear here)
   */
  manualEvents?: (number | Event)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventsCalendar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MusiciansGridBlock".
 */
export interface MusiciansGridBlock {
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Optional — leave empty to show all by order
   */
  musicians?: (number | Musician)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'musiciansGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecurringSeriesTeaserBlock".
 */
export interface RecurringSeriesTeaserBlock {
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Optional — leave empty to show all
   */
  series?: (number | RecurringSery)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'recurringSeriesTeaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsCarouselBlock".
 */
export interface NewsCarouselBlock {
  eyebrow?: string | null;
  heading?: string | null;
  viewAllLabel?: string | null;
  viewAllUrl?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomSelectorBlock".
 */
export interface RoomSelectorBlock {
  heading?: string | null;
  /**
   * Optional. Leave empty to show all rooms by their order.
   */
  rooms?: (number | Room)[] | null;
  equipmentHeading?: string | null;
  offerHeading?: string | null;
  offerItems?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'roomSelector';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferCardsBlock".
 */
export interface OfferCardsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  cards?:
    | {
        image?: (number | null) | Media;
        tag?: string | null;
        title?: string | null;
        body?: string | null;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'offerCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SalesContactBlock".
 */
export interface SalesContactBlock {
  heading?: string | null;
  teamMember?: (number | null) | TeamMember;
  callLabel?: string | null;
  emailLabel?: string | null;
  style?: ('gold' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'salesContact';
}
/**
 * Team members and staff shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role?: string | null;
  phone?: string | null;
  email?: string | null;
  photo?: (number | null) | Media;
  /**
   * Controls display order (lower numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EveningPhasesBlock".
 */
export interface EveningPhasesBlock {
  heading?: string | null;
  phases?:
    | {
        image?: (number | null) | Media;
        title?: string | null;
        timeLabel?: string | null;
        body?: string | null;
        primaryCtaLabel?: string | null;
        primaryCtaUrl?: string | null;
        secondaryCtaLabel?: string | null;
        secondaryCtaUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eveningPhases';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock".
 */
export interface ContactInfoBlock {
  showForm?: boolean | null;
  formHeading?: string | null;
  showMap?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapEmbedBlock".
 */
export interface MapEmbedBlock {
  /**
   * Google Maps iframe src URL
   */
  embedUrl?: string | null;
  height?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArtistCtaBlock".
 */
export interface ArtistCtaBlock {
  eyebrow?: string | null;
  heading?: string | null;
  backgroundImage?: (number | null) | Media;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'artistCTA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Notice21PlusBlock".
 */
export interface Notice21PlusBlock {
  heading?: string | null;
  body?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'notice21Plus';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterCtaBlock".
 */
export interface NewsletterCtaBlock {
  heading?: string | null;
  body?: string | null;
  placeholder?: string | null;
  buttonLabel?: string | null;
  consentText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterCTA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArtistFormBlock".
 */
export interface ArtistFormBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'artistForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  reviewSummary?: string | null;
  items?:
    | {
        name: string;
        stars: number;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * Categories that group menu items (e.g. Nikaragua, Przystawki, Koktajle).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  title: string;
  menuType: 'cigars' | 'cocktails' | 'wine' | 'food';
  /**
   * Controls display order (lower numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual menu items — cocktails, food, wine and cigars.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Ingredients list (mainly for cocktails)
   */
  ingredients?: string | null;
  menuType: 'cigars' | 'cocktails' | 'wine' | 'food';
  category?: (number | null) | MenuCategory;
  price?: number | null;
  currency?: string | null;
  image?: (number | null) | Media;
  /**
   * Country or region of origin
   */
  origin?: string | null;
  /**
   * Variants of this item (e.g. SMASH BURGER CLASSIC / BBQ)
   */
  variants?:
    | {
        label?: string | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  tag?: string | null;
  /**
   * Controls display order (lower numbers first)
   */
  order?: number | null;
  available?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer reviews and testimonials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  rating?: number | null;
  text: string;
  source?: ('google' | 'other') | null;
  featured?: boolean | null;
  /**
   * Controls display order (lower numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the public artist contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artist-applications".
 */
export interface ArtistApplication {
  id: number;
  fullName: string;
  phone?: string | null;
  email: string;
  city?: string | null;
  instrument?: string | null;
  genres?: string | null;
  preferredLineup?: ('solo' | 'duo' | 'trio' | 'quartet' | 'band' | 'other') | null;
  bandName?: string | null;
  rateProposal?: string | null;
  dateProposals?: string | null;
  repertoire?: string | null;
  musicEducation?: ('none' | 'inProgress' | 'secondary' | 'higher') | null;
  schoolName?: string | null;
  educationDetails?: string | null;
  stageExperience?: ('none' | 'some' | 'experienced' | 'professional') | null;
  pastVenues?: string | null;
  recordings?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  facebook?: string | null;
  instagram?: string | null;
  message?: string | null;
  status?: ('new' | 'reviewed' | 'contacted') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'musicians';
        value: number | Musician;
      } | null)
    | ({
        relationTo: 'recurring-series';
        value: number | RecurringSery;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'artist-applications';
        value: number | ArtistApplication;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        pageHero?: T | PageHeroBlockSelect<T>;
        heroBanner?:
          | T
          | {
              heading?: T;
              subtext?: T;
              backgroundImage?: T;
              backgroundVideoUrl?: T;
              secondaryLinks?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    icon?: T;
                    id?: T;
                  };
              ctaLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              ctaIcon?: T;
              id?: T;
              blockName?: T;
            };
        aboutIntro?: T | AboutIntroBlockSelect<T>;
        bentoSection?: T | BentoSectionBlockSelect<T>;
        menuSection?: T | MenuSectionBlockSelect<T>;
        setMenu?: T | SetMenuBlockSelect<T>;
        promoBand?: T | PromoBandBlockSelect<T>;
        eventsTeaser?: T | EventsTeaserBlockSelect<T>;
        specialEvents?: T | SpecialEventsBlockSelect<T>;
        eventsCalendar?: T | EventsCalendarBlockSelect<T>;
        musiciansGrid?: T | MusiciansGridBlockSelect<T>;
        recurringSeriesTeaser?: T | RecurringSeriesTeaserBlockSelect<T>;
        newsCarousel?: T | NewsCarouselBlockSelect<T>;
        roomSelector?: T | RoomSelectorBlockSelect<T>;
        offerCards?: T | OfferCardsBlockSelect<T>;
        salesContact?: T | SalesContactBlockSelect<T>;
        eveningPhases?: T | EveningPhasesBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        mapEmbed?: T | MapEmbedBlockSelect<T>;
        artistCTA?: T | ArtistCtaBlockSelect<T>;
        notice21Plus?: T | Notice21PlusBlockSelect<T>;
        newsletterCTA?: T | NewsletterCtaBlockSelect<T>;
        artistForm?: T | ArtistFormBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        liveStream?:
          | T
          | {
              title?: T;
              embedUrl?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              columns?:
                | T
                | {
                    size?: T;
                    richText?: T;
                    enableLink?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              richText?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              id?: T;
              blockName?: T;
            };
        archive?:
          | T
          | {
              introContent?: T;
              populateBy?: T;
              relationTo?: T;
              categories?: T;
              limit?: T;
              selectedDocs?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              style?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock_select".
 */
export interface PageHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleStyle?: T;
  backgroundImage?: T;
  inlineLinkLabel?: T;
  inlineLinkUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutIntroBlock_select".
 */
export interface AboutIntroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  body?: T;
  pullQuote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoSectionBlock_select".
 */
export interface BentoSectionBlockSelect<T extends boolean = true> {
  subheading?: T;
  heading?: T;
  description?: T;
  items?:
    | T
    | {
        image?: T;
        colSpan?: T;
        label?: T;
        title?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenuSectionBlock_select".
 */
export interface MenuSectionBlockSelect<T extends boolean = true> {
  sectionTag?: T;
  heading?: T;
  menuType?: T;
  layout?: T;
  groupByCategory?: T;
  pdfDownload?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SetMenuBlock_select".
 */
export interface SetMenuBlockSelect<T extends boolean = true> {
  heading?: T;
  dateLabel?: T;
  menus?:
    | T
    | {
        name?: T;
        price?: T;
        courses?:
          | T
          | {
              courseLabel?: T;
              dish?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBandBlock_select".
 */
export interface PromoBandBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  image?: T;
  items?:
    | T
    | {
        label?: T;
        sub?: T;
        price?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  relatedEvent?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsTeaserBlock_select".
 */
export interface EventsTeaserBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  viewAllLabel?: T;
  viewAllUrl?: T;
  limit?: T;
  onlyFeatured?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecialEventsBlock_select".
 */
export interface SpecialEventsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsCalendarBlock_select".
 */
export interface EventsCalendarBlockSelect<T extends boolean = true> {
  variant?: T;
  colorScheme?: T;
  heading?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  eventsSource?: T;
  autoCount?: T;
  manualEvents?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MusiciansGridBlock_select".
 */
export interface MusiciansGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  musicians?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecurringSeriesTeaserBlock_select".
 */
export interface RecurringSeriesTeaserBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  series?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsCarouselBlock_select".
 */
export interface NewsCarouselBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  viewAllLabel?: T;
  viewAllUrl?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomSelectorBlock_select".
 */
export interface RoomSelectorBlockSelect<T extends boolean = true> {
  heading?: T;
  rooms?: T;
  equipmentHeading?: T;
  offerHeading?: T;
  offerItems?:
    | T
    | {
        item?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferCardsBlock_select".
 */
export interface OfferCardsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  cards?:
    | T
    | {
        image?: T;
        tag?: T;
        title?: T;
        body?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SalesContactBlock_select".
 */
export interface SalesContactBlockSelect<T extends boolean = true> {
  heading?: T;
  teamMember?: T;
  callLabel?: T;
  emailLabel?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EveningPhasesBlock_select".
 */
export interface EveningPhasesBlockSelect<T extends boolean = true> {
  heading?: T;
  phases?:
    | T
    | {
        image?: T;
        title?: T;
        timeLabel?: T;
        body?: T;
        primaryCtaLabel?: T;
        primaryCtaUrl?: T;
        secondaryCtaLabel?: T;
        secondaryCtaUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock_select".
 */
export interface ContactInfoBlockSelect<T extends boolean = true> {
  showForm?: T;
  formHeading?: T;
  showMap?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapEmbedBlock_select".
 */
export interface MapEmbedBlockSelect<T extends boolean = true> {
  embedUrl?: T;
  height?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArtistCtaBlock_select".
 */
export interface ArtistCtaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  backgroundImage?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Notice21PlusBlock_select".
 */
export interface Notice21PlusBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterCtaBlock_select".
 */
export interface NewsletterCtaBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  placeholder?: T;
  buttonLabel?: T;
  consentText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArtistFormBlock_select".
 */
export interface ArtistFormBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  reviewSummary?: T;
  items?:
    | T
    | {
        name?: T;
        stars?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  publishedAt?: T;
  authors?: T;
  categories?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  eventType?: T;
  leadTitle?: T;
  description?: T;
  image?: T;
  posterImage?: T;
  date?: T;
  endTime?: T;
  price?: T;
  featured?: T;
  room?: T;
  recurringSeries?: T;
  genres?: T;
  performers?:
    | T
    | {
        musician?: T;
        instrument?: T;
        id?: T;
      };
  descriptionHeading?: T;
  body?: T;
  ticketUrl?: T;
  reservationUrl?: T;
  shareEnabled?: T;
  performersHeading?: T;
  shareLabel?: T;
  showUpcoming?: T;
  upcomingHeading?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "musicians_select".
 */
export interface MusiciansSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  instrument?: T;
  role?: T;
  photo?: T;
  heroImage?: T;
  bio?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-series_select".
 */
export interface RecurringSeriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  wordmarkImage?: T;
  heroImage?: T;
  themeColor?: T;
  eyebrow?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  upcomingHeading?: T;
  upcomingCount?: T;
  seeProgrammeLabel?: T;
  showOtherSeries?: T;
  otherSeriesHeading?: T;
  showNews?: T;
  newsHeading?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  title?: T;
  menuType?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  ingredients?: T;
  menuType?: T;
  category?: T;
  price?: T;
  currency?: T;
  image?: T;
  origin?: T;
  variants?:
    | T
    | {
        label?: T;
        price?: T;
        id?: T;
      };
  tag?: T;
  order?: T;
  available?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  capacity?: T;
  description?: T;
  equipment?:
    | T
    | {
        item?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  email?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  rating?: T;
  text?: T;
  source?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artist-applications_select".
 */
export interface ArtistApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  city?: T;
  instrument?: T;
  genres?: T;
  preferredLineup?: T;
  bandName?: T;
  rateProposal?: T;
  dateProposals?: T;
  repertoire?: T;
  musicEducation?: T;
  schoolName?: T;
  educationDetails?: T;
  stageExperience?: T;
  pastVenues?: T;
  recordings?:
    | T
    | {
        url?: T;
        id?: T;
      };
  facebook?: T;
  instagram?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Site logo shown in the header
   */
  logo?: (number | null) | Media;
  /**
   * Announcement text shown in the top bar
   */
  topBarText?: string | null;
  /**
   * Phone number shown in the top bar
   */
  phone?: string | null;
  /**
   * Physical address shown in the top bar
   */
  address?: string | null;
  /**
   * Navigation links shown to the left of the logo
   */
  navItemsLeft?:
    | {
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Navigation links shown to the right of the logo
   */
  navItemsRight?:
    | {
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  ctaEnabled?: boolean | null;
  /**
   * Call-to-action button (e.g., Reservation / Rezerwacja)
   */
  ctaButton?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Logo shown in the footer
   */
  logo?: (number | null) | Media;
  newsletter?: {
    heading?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
    consentText?: string | null;
  };
  ageBadge?: boolean | null;
  navColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomBarLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  address?: string | null;
  phones?:
    | {
        label?: string | null;
        number?: string | null;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        label?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Single source of truth for social links across the whole site (header, mobile menu, footer, SEO). Edit here once — updates everywhere.
   */
  social?:
    | {
        platform: 'google' | 'facebook' | 'instagram' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  mapEmbedUrl?: string | null;
  /**
   * Default booking / ticket link
   */
  reservationUrl?: string | null;
  reviewAggregate?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-hours".
 */
export interface OpeningHour {
  id: number;
  days?:
    | {
        day?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
        closed?: boolean | null;
        openTime?: string | null;
        closeTime?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  regulamin?: string | null;
  privacy?: string | null;
  companyData?: string | null;
  age21Notice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  topBarText?: T;
  phone?: T;
  address?: T;
  navItemsLeft?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  navItemsRight?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  ctaEnabled?: T;
  ctaButton?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  newsletter?:
    | T
    | {
        heading?: T;
        placeholder?: T;
        buttonLabel?: T;
        consentText?: T;
      };
  ageBadge?: T;
  navColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  bottomBarLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  address?: T;
  phones?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        label?: T;
        email?: T;
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  mapEmbedUrl?: T;
  reservationUrl?: T;
  reviewAggregate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-hours_select".
 */
export interface OpeningHoursSelect<T extends boolean = true> {
  days?:
    | T
    | {
        day?: T;
        closed?: T;
        openTime?: T;
        closeTime?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  regulamin?: T;
  privacy?: T;
  companyData?: T;
  age21Notice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}